### ISSUE TITLE
Could not resolve "util"

### ISSUE THREAD

**Issue by bartonhammond** [NeuraLegion/cypress-har-generator#167]
**Description**
```
node --version
v18.12.1
```

On Windows 10, using Cucumber, when executing Feature, get following error
```
Error: Build failed with 5 errors:
node_modules/@neuralegion/cypress-har-generator/commands.js:1:221: ERROR: Could not resolve "util"
node_modules/@neuralegion/cypress-har-generator/commands.js:1:254: ERROR: Could not resolve "fs"
node_modules/@neuralegion/cypress-har-generator/commands.js:1:268: ERROR: Could not resolve "crypto"
node_modules/@neuralegion/cypress-har-generator/commands.js:1:286: ERROR: Could not resolve "os"
node_modules/@neuralegion/cypress-har-generator/commands.js:1:300: ERROR: Could not resolve "path"
```

**Steps to reproduce**
`package.json` 
```
 "devDependencies": {
    "@neuralegion/cypress-har-generator": "^5.12.1",
    "cypress": "^12.3.0"
```
`support\index.js`
```require('@neuralegion/cypress-har-generator/commands');```

`cypress.config.js`
```
const { install } = require("@neuralegion/cypress-har-generator");
...

module.exports = defineConfig({
  e2e: {
    async setupNodeEvents(on, config) {
      const bundler = createBundler({
        plugins: [createEsbuildPlugin(config)],
      });
      install(on);
      on("file:preprocessor", bundler);
      await addCucumberPreprocessorPlugin(on, config);
...
```

**Expected behavior**
That the Feature runs the Scenario w/o errors

**Actual behavior**
```
Error: Build failed with 5 errors:
node_modules/@neuralegion/cypress-har-generator/commands.js:1:221: ERROR: Could not resolve "util"
node_modules/@neuralegion/cypress-har-generator/commands.js:1:254: ERROR: Could not resolve "fs"
node_modules/@neuralegion/cypress-har-generator/commands.js:1:268: ERROR: Could not resolve "crypto"
node_modules/@neuralegion/cypress-har-generator/commands.js:1:286: ERROR: Could not resolve "os"
node_modules/@neuralegion/cypress-har-generator/commands.js:1:300: ERROR: Could not resolve "path"
    at failureErrorWithLog (C:\Users\hammonbu\git\smc-cypress\node_modules\esbuild\lib\main.js:1605:15)
    at C:\Users\hammonbu\git\smc-cypress\node_modules\esbuild\lib\main.js:1251:28
    at runOnEndCallbacks (C:\Users\hammonbu\git\smc-cypress\node_modules\esbuild\lib\main.js:1034:63)
    at buildResponseToResult (C:\Users\hammonbu\git\smc-cypress\node_modules\esbuild\lib\main.js:1249:7)
    at C:\Users\hammonbu\git\smc-cypress\node_modules\esbuild\lib\main.js:1358:14
    at C:\Users\hammonbu\git\smc-cypress\node_modules\esbuild\lib\main.js:666:9
    at handleIncomingPacket (C:\Users\hammonbu\git\smc-cypress\node_modules\esbuild\lib\main.js:763:9)
    at Socket.readFromStdout (C:\Users\hammonbu\git\smc-cypress\node_modules\esbuild\lib\main.js:632:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
```

**Screenshots**

**Comment by derevnjuk** [comment]
@bartonhammond thanks for the report. I'm trying to provide a fix as soon as possible.

**Comment by derevnjuk** [comment]
@bartonhammond [v5.12.2](https://github.com/NeuraLegion/cypress-har-generator/releases/tag/v5.12.2) has just been released.

**Comment by bartonhammond** [comment]
@derevnjuk Awesome!  Works like a charm!  Thanks
