### ISSUE TITLE
ERR_IPC_CHANNEL_CLOSED error when running in Gitlab

### ISSUE THREAD

**Issue by kalpeshchilka** [NeuraLegion/cypress-har-generator#62]
When running our e2e test with the cypress-har-generator plugin, it fails on Gitlab and throws the below errors. Tried running the same e2e test scenarios without this plugin enabled and it working fine.

Using below versions:
cypress-har-generator plugin -- 5.2.3
cypress -- 6.4.0

Below console error from Gitlab:

`The following error was thrown by a plugin. We stopped running your tests because a plugin crashed. Please check your plugins file (`/tests/e2e/cypress/plugins/index.js`)
 Error [ERR_IPC_CHANNEL_CLOSED] [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at ChildProcess.target.send (internal/child_process.js:679:16)`

`Warning: We failed processing this video.
This error will not alter the exit code.
TimeoutError: operation timed out
    at afterTimeout (/node_modules/cypressBinaryCache/6.4.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/timers.js:46:19)
    at Timeout.timeoutTimeout [as _onTimeout] (/node_modules/cypressBinaryCache/6.4.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/timers.js:76:13)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
Warning: We could not find the video at the following path, so we were unable to process it.
Video path: /videos/test.spec.js.mp4
This error will not alter the exit code.`

Before getting the plugin crash error, also got the memory leakage error as mentioned below:
`(node:548) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 preprocessor:close listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit`

Thus did some research on google but didn't get any concrete solution for this. Below are the reference links with this plugin crash or memory leakage issue.
* https://github.com/cypress-io/cypress/issues/1305
* https://github.com/gatsbyjs/gatsby/issues/9027#issuecomment-432004663
* https://github.com/cypress-io/cypress/issues/1968

I was even referring to an already reported issue but for CircleCI which is marked as close -- https://github.com/NeuraLegion/cypress-har-generator/issues/23

Any help or workaround for this issue will be really appreciated. Thanks in advance!

**Comment by derevnjuk** [comment]
Closing due to inactivity. @kalpeshchilka please let me know if you still experience this issue.
